In [1]:
#Exercise 1
import numpy as np

In [4]:
#Exercise 2
(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = [

In [5]:
#Exercise 3
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#Exercise 4
data = np.array([1, 2, 3])
print("%d bytes" % (data.size * data.itemsize))

12 bytes


In [26]:
#Exercise 5
np.lookfor('add')

Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Add documentation to an existing object, typically one defined in C
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy._add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.fft.test
    Pytest test runner.
numpy.ma.append
    Append values to the end of an array.
numpy.bytes0.ljust
    Return a left-justified string of length width.
numpy.bytes0.rju

In [32]:
#Exercise 6

x = np.zeros(10)

x[4]= 1
 
print(x)




[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [44]:
#Exercise 7
import numpy as np

x = np.arange(30)
b = x+10

print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [54]:
#Exercise 8


x = np.arange(30)
b= np.flip(x, axis=None)
print(b)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


In [57]:
#Exercise 9

b= np.arange(9)

b = b.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
#Exercise 10

x = np.array([1,2,0,0,4,0])
x =np.where(x != 0)[0]
print(x)


[0 1 4]


In [61]:
#Exercise 11

x =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]]


In [62]:
#Exercise 12
x = np.random.normal(size=(3,3))

print(x)

[[ 0.54887663  0.42772855  1.42969035]
 [-1.91424818 -1.26096627  1.53121951]
 [-1.12743211  1.63896889 -0.76494006]]


In [2]:
#Exercise 13
x = np.random.normal(size=(10,10))
max = np.amax(x)
min = np.amin(x)

print(x)
print(max)
print(min)

[[-0.06500628 -0.5064209  -0.03557808 -0.64843879  0.22020327 -0.49244278
  -1.14191758  0.0959376   0.15187091  0.51842604]
 [ 0.65249045  0.99817446  1.58816301  0.42515446 -0.53098766  0.18092288
  -0.47012734  0.93224088 -0.8391895  -0.80079903]
 [ 0.05333547  0.95168882 -0.61604009  0.74603659 -1.26631444 -0.06481809
  -0.00667271 -2.12749573  2.40632813  0.67400167]
 [-0.32969202 -0.64519411  0.72418448  1.43483742 -1.19750816 -0.89876686
   0.54573358 -1.08428805  1.95694205  1.03733853]
 [ 2.67712677 -1.21713203  0.78775604  0.89543243  0.84573039 -0.03280022
  -0.40531658 -0.35683405  0.38589093  1.08425487]
 [ 1.20769232  0.70021475  1.92531814 -0.66523847  1.3088169  -0.96192083
  -0.13680255 -0.83463534  0.46403022  0.84733424]
 [ 0.40906467  1.1259352   0.04898639  0.39019746  1.18028551 -0.87876664
   0.37672311  0.53442943  0.36467188  1.59997495]
 [-0.90161641 -1.60086864  0.28685643  1.05241917  1.51357884  0.37827419
   0.85926787  0.77903337  1.91073671  0.73607567]


In [65]:
#Exercise 14
x = np.random.normal(size=(1,30))
max = np.amax(x)
min = np.amin(x)


print(x)
print((max + min)/2)

[[ 0.21110534  0.52402134  1.10790033 -0.11059566 -0.68493844 -0.38115562
   0.72601881  0.39203328 -0.92085598  1.35985984 -0.88733708  1.31737704
  -1.43553995 -1.60202703 -0.17503191 -0.15301962  0.79122579 -0.63429549
   0.58633201  0.31258842 -0.08185647 -0.78571689  0.03070938 -1.66808457
   0.32014262  1.3255798  -0.08831546  0.35838836  2.37650039 -0.49674082]]
0.3542079120574748


In [3]:
#Exercise 15
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
#Exercise 16 . This one I did not fully understand the question

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
#Exercise 17
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [7]:
#Exercise 18
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [8]:
#Exercise 19 - ask why <

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
#Exercise 20
x = np.arange(336)
x = x.reshape(6,7,8)
result = np.where(x == 100)

print(x)
print(result)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [11]:
#Exercise 21
#arr1 = np.arange(2) 
#x1 = np.tile(arr1, 4)

#arr2 = np.array([1,0]) 
#x2 = np.tile(arr2, 4)

#print(x1)
#print(x2)
#print(x1)
#print(x2)
#print(x1)
#print(x2)
#print(x1)
#print(x2)


Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
#Exercise 22
#22. Normalize a 5x5 random matrix 
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


[[-0.91710421  0.24836595  1.73470144  0.2899409   0.75431426]
 [-1.62564889  0.0111851   1.49966753 -0.41915272  0.02689461]
 [ 0.44230641  1.14688662 -0.1212937   1.41601138 -1.12227868]
 [-1.35877399  1.25588095  0.08737604 -1.60345084 -1.55659216]
 [-0.69816233  0.22491807 -0.03073341  1.04132636 -0.72658467]]


In [13]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-13-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [1]:
#Exercise 24 - Assignment not clear

In [4]:
#Exercise 25

x = np.random.normal(size=(5,3))
x2 = np.random.normal(size=(3,2))

print(np.dot(x,x2))

[[-1.08968901 -3.83015754]
 [ 2.15407449  2.37811969]
 [-0.83975158 -0.41813823]
 [ 1.38850553 -5.79326604]
 [-0.01091719 -4.52746356]]


In [5]:
#Ex. 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [11]:
#Ex. 27
Z = 2

#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z

#what do you mean by legal? they all work

False

In [15]:
#Ex.28
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-15-796f86c3c15d>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-15-796f86c3c15d>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [16]:
#Ex. 29 Not understood

In [17]:
#Ex. 30
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [18]:
#Ex.31
np.seterr(all='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [19]:
#Ex.32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [21]:
#Ex. 33
today     = np.datetime64('today', 'D')
print("Today: ",today)

Today:  2021-01-06


In [24]:
#Ex.34


In [25]:
#Ex.35 Not understood

In [4]:
#Ex.36
x = np.random.normal(size=(5,5))

x = x.astype(int)
print(x)


[[ 1 -1  0  1  0]
 [ 1  0  0  0  0]
 [ 0  1  1 -2  0]
 [ 0 -1  0  0  0]
 [ 0  0 -1  0  0]]


In [13]:
#Ex. 37
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
#Ex. 38
iterable = (a*a for a in range(10))
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
#Ex. 39
np.linspace(0.1, 1, num=10 ,endpoint=False)

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

In [24]:
#ex.40
x = np.random.normal(size=(10))
np.sort(x)

array([-0.83965827, -0.64459081, -0.48512512, -0.18657653,  0.22006425,
        0.3443278 ,  0.53259613,  0.61681702,  0.78233544,  1.79873973])

In [26]:
#Ex.41
a = np.arange(4).reshape(2, 2) 
np.add.reduce(a) 

array([2, 4])

In [27]:
#Ex.42
np.array_equal(x,a)

False

In [28]:
#Ex.43
a.flags.writeable=False

In [ ]:
#Ex.44
