In [1]:
#Exercise 1
import numpy as np

In [4]:
#Exercise 2
(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3/envs/Test_env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = [

In [5]:
#Exercise 3
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#Exercise 4
data = np.array([1, 2, 3])
print("%d bytes" % (data.size * data.itemsize))

12 bytes


In [26]:
#Exercise 5
np.lookfor('add')

Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Add documentation to an existing object, typically one defined in C
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy._add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.fft.test
    Pytest test runner.
numpy.ma.append
    Append values to the end of an array.
numpy.bytes0.ljust
    Return a left-justified string of length width.
numpy.bytes0.rju

In [32]:
#Exercise 6

x = np.zeros(10)

x[4]= 1
 
print(x)




[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [44]:
#Exercise 7
import numpy as np

x = np.arange(30)
b = x+10

print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [54]:
#Exercise 8


x = np.arange(30)
b= np.flip(x, axis=None)
print(b)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


In [57]:
#Exercise 9

b= np.arange(9)

b = b.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
#Exercise 10

x = np.array([1,2,0,0,4,0])
x =np.where(x != 0)[0]
print(x)


[0 1 4]


In [61]:
#Exercise 11

x =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]]


In [62]:
#Exercise 12
x = np.random.normal(size=(3,3))

print(x)

[[ 0.54887663  0.42772855  1.42969035]
 [-1.91424818 -1.26096627  1.53121951]
 [-1.12743211  1.63896889 -0.76494006]]


In [63]:
#Exercise 13
x = np.random.normal(size=(10,10))
max = np.amax(x)
min = np.amin(x)

print(x)
print(max)
print(min)

[[ 0.92638146 -1.05020923  0.39942137  0.57711455 -0.18299662  0.74145942
  -0.86662675  0.66810586  0.05720997  0.699624  ]
 [ 0.65271456 -0.76617554 -0.67548005 -0.23821519  0.77541612  2.29126331
   0.5881008  -0.99149819 -0.39768759 -1.55596231]
 [-1.80402005 -0.09168151 -1.88486024 -0.01417615 -0.22998565 -2.30459177
   0.28511526 -0.15288682  0.60100733 -1.25074561]
 [ 1.90323509  1.47848219 -2.75367767  0.9585729  -1.56686707 -0.2561849
   0.81525178  0.75204562  0.26869573 -1.03672496]
 [-0.80818623  0.25537026 -0.02235951  0.81766622  0.01803871  2.0388354
   1.17681394  0.78422193  1.4742024   0.31888377]
 [ 1.36324725 -0.81952701  0.79955716  0.52821754 -2.0943559   1.39202304
  -0.68846879  0.49277624  0.15355461  1.79909881]
 [ 1.03253299  0.05429968 -0.12538187  0.20573953  0.15492237  0.60100304
  -1.05043161  0.46994199 -1.81033441  0.85336594]
 [ 1.30802096 -1.65009503  0.46211674 -1.2187688  -1.32124663 -2.4818249
  -0.72666767 -0.10194233 -0.81972385 -1.07637413]
 [-

In [65]:
#Exercise 14
x = np.random.normal(size=(1,30))
max = np.amax(x)
min = np.amin(x)


print(x)
print((max + min)/2)

[[ 0.21110534  0.52402134  1.10790033 -0.11059566 -0.68493844 -0.38115562
   0.72601881  0.39203328 -0.92085598  1.35985984 -0.88733708  1.31737704
  -1.43553995 -1.60202703 -0.17503191 -0.15301962  0.79122579 -0.63429549
   0.58633201  0.31258842 -0.08185647 -0.78571689  0.03070938 -1.66808457
   0.32014262  1.3255798  -0.08831546  0.35838836  2.37650039 -0.49674082]]
0.3542079120574748


In [75]:
#Exercise 15
x = np.ones([2,3])
x[0,1] = 0
x[1,1] = 0
print(x)

[[1. 0. 1.]
 [1. 0. 1.]]


In [76]:
#Exercise 16 . This one I did not fully understand the question

x = np.ones([2,3])
x[0,1] = 0
x[1,1] = 0
print(x)


[[1. 0. 1.]
 [1. 0. 1.]]


In [80]:
#Exercise 17
True

True

In [94]:
#Exercise 18
x = np.tri(5, 5, 0, dtype=int)


x[1,0] = 2
x[1,1] = 3
x[2,0] = 4
x[2,1] = 5
x[2,2] = 1
x[3,0] = 2
x[3,1] = 3
x[3,2] = 4
x[3,3] = 5
x[3,4] = 0
x[4,0] = 2
x[4,1] = 3
x[4,2] = 4
x[4,3] = 5
x[4,4] = 1

print(x)

[[1 0 0 0 0]
 [2 3 0 0 0]
 [4 5 1 0 0]
 [2 3 4 5 0]
 [2 3 4 5 1]]


In [131]:
#Exercise 19

x1 = np.array([0,1,0,1,0,1,0,1])
x2 = np.array([1,0,1,0,1,0,1,0])

print(x1)
print(x2)
print(x1)
print(x2)
print(x1)
print(x2)
print(x1)
print(x2)

[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]


In [118]:
#Exercise 20
x = np.arange(336)
x = x.reshape(6,7,8)
result = np.where(x == 100)

print(x)
print(result)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [134]:
#Exercise 21
arr1 = np.arange(2) 
x1 = np.tile(arr1, 4)

arr2 = np.array([1,0]) 
x2 = np.tile(arr2, 4)

print(x1)
print(x2)
print(x1)
print(x2)
print(x1)
print(x2)
print(x1)
print(x2)

[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]


In [ ]:
#Exercise 22
#22. Normalize a 5x5 random matrix 

