In [8]:
import numpy as np
import math

a = np.array([3,1,2])
b = np.array([-5,4,1])
c= np.array([0,3,-8])

A = np.stack([a,b,c])



d = np.array([0,5,-1])
e = np.array([3,2,-1])
f = np.array([10,0.5,4])

B = np.stack([d,e,f])


C = np.cross(A,B)

print(C)
print(C[1,2])

[[-11.   3.  15.]
 [ -6.  -2. -22.]
 [ 16. -80. -30.]]
-22.0


In [9]:
def inverse_matrix(A):
    mat_inv = np.linalg.inv(A)
    return mat_inv

b = np.array([[1., 2.], [3., 4.]])


inverse_matrix(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
A = np.array([[3, 0.6, 4, -3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3 , 9],[-9, 0,0,0]])
C = np.array([[0,1009, -66.7849, 90],[0,5,4,-0.07],[-7.7,0,0,0]])

D = A + B - C

D[1][2]

-2.7

In [11]:
D[2][0]


5.7

In [12]:
AA = np.array([0.6,-15,2,5,98])
BB = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

CC = np.dot(AA.T, BB)
CC

array([-102.8,  255.2,  595.6])

In [13]:
CC[2]

595.6